server:
  port: 9090

spring:
  application:
    name: gateway

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    request:
      path: /request/**
      url: http://localhost:9098
      #stripPrefix: false