server:
  port: 9090

spring:
  application:
    name: gateway

zuul:
  routes:
    identity:
      path: /identity/**
      url: http://localhost:9099
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
    request:
      path: /request/**
      url: http://localhost:9098

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/