CREATE TABLE IF NOT EXISTS USERROLE (
  id_role integer PRIMARY KEY AUTO_INCREMENT,
  rolename VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS USERAPP (
  id integer PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(320) NOT NULL,
  password VARCHAR(45) NOT NULL,
  id_role integer, FOREIGN KEY (id_role) REFERENCES USERROLE (id_role)
);