server:
  port: 9098

spring:
  application:
    name: request

zuul:
  routes:
    identity:
      path: /identity/**
      url: http://localhost:9099

    request:
      path: /request/**
      url: http://localhost:9098
      #stripPrefix: false

currency:
  main : http://currencies.apps.grandtrunk.net/getlatest/%s/%s

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/