CREATE TABLE IF NOT EXISTS QUOTES (
  id integer PRIMARY KEY AUTO_INCREMENT,
  date TIMESTAMP,
  currencyname VARCHAR(10) NOT NULL,
  period VARCHAR(20) NOT NULL,
  open DECIMAL NOT NULL,
  close DECIMAL NOT NULL,
  hight DECIMAL NOT NULL,
  low DECIMAL NOT NULL
);