version: '2'

services:
  nginx:
    build: ./
    ports:
      - 88:80
    volumes:
      - ./dist:/var/www/frontend
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/logs/nginx/:/var/log/nginx
